import Head from "next/head";
import SingleblogPage from "../../components/Blog/SingleBlogPage";
import Navbar from "../../components/Navbar";
import BlogService from "../../services/Blog";

const SingleBlog = ({ blog }) => {
  return (
    <>
      <Head>
        <title>Single Blog Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <SingleblogPage blog={blog} />

       
    </>
  );
};

export default SingleBlog;

export async function getServerSideProps({ req, query }) {
  const blogID = query.id;
  const blog = await BlogService.getSingleBlog(blogID)
    .then((resp) => resp?.data)
    .catch(() => error);
  return {
    props: {
      blog,
    },
  };
}
